version: "3.3"
networks:
  LAMP:
services:
  php-apache:
    container_name: 'PHP-APACHE'
    build:
      context: .
      dockerfile: 'Dockerfile'
    restart: always
    links:
      - "postgres:localhost"
    ports:
      - "80:80"
    user: '1000:1000'
    volumes:
      - './apache_conf:/etc/apache2/sites-available/'
      - ./:/var/www/html
    depends_on:
      - postgres
    networks:
      - LAMP
  postgres:
    container_name: "PostgreSQL"
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_USER: sinstranger
      POSTGRES_PASSWORD: example
      TZ: Europe/Moscow
    ports:
      - "5432:5432"
    networks:
      - LAMP
  Adminer:
    container_name: "ADMINER"
    image: "adminer:latest"
    restart: always
    environment:
      ADMINER_DESIGN: pappu687
    ports:
      - "8080:8080"
    links:
      - "postgres:db"
    depends_on:
      - postgres
    networks:
      - LAMP