version: "3.3"
services:
  php-apache:
    container_name: 'PHP-APACHE'
    build:
      context: .
      dockerfile: 'Dockerfile'
    restart: always
    links:
      - 'MariaDb:localhost'
    ports:
      - "80:80"
    user: '1000:1000'
    volumes:
      - './apache_conf:/etc/apache2/sites-available/'
      - ./:/var/www/html
    depends_on:
      - MariaDb
  MariaDb:
    image: "mariadb:latest"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: sinstranger
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: shop
    ports:
     - "3306:3306"
  Adminer:
    image: "adminer:latest"
    restart: always
    environment:
      ADMINER_DESIGN: pappu687
    ports:
      - "8080:8080"
    links:
      - "MariaDb:db"
    depends_on:
      - MariaDb